// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations precisam de uma conexão direta (não-pooled): o
    // `prisma migrate deploy` usa advisory locks do Postgres, que não
    // funcionam através do pooler (PgBouncer) do Neon e resultam em
    // "P1002 / Timed out trying to acquire a postgres advisory lock".
    // Em produção, defina DIRECT_URL apontando para o host sem `-pooler`.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
